baseurl = "http://ashblog.ru/"
languageCode = "ru-RU"
title = ".ash"
#uglyurls = true
MetaDataFormat = "toml"
theme = "slender"
paginate = 5
PaginatePath = "/"
pluralizelisttitles = false
disqusShortname = "biogenez"

[author]
    name = "alexander"
    
[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = ".дом"
    url        = "/"
    weight     = 0

    [[menu.main]]
    identifier = "sp"
    name       = ".sp"
    url        = "sp/"
    weight     = 1

    [[menu.main]]
    identifier = "about"
    name       = ".я"
    url        = "about/"
    weight     = 2
    
[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = "LIV"
    
    # Footer; Markdown accepted here.
    footer = "-"
    
    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    #email = "mailto:your-email"
    #github = "url-to-your-github"
    #bitbucket = "url-to-your-bitbucket"
    #twitter = "url-to-your-twitter"
    #stackoverflow = "url-to-your-stackoverflow"
    #linkedin = "url-to-your-linkedin"
    facebook = "https://www.facebook.com/a.shelopukho"
    instagram = "https://www.instagram.com/biogenez"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = "UA-50925053-3"

    #cdn url (azure cdn)
    cdn = "http://ashblog.azureedge.net"